from enum import Enum


class TiposTermo(Enum):
    TODOS = "t"
    PESSOAS = "p"
    INSTITUICOES = "i"
    PATENTES = "pa"
    DIARIOS_OFICIAIS = "d"
    ENVOLVIDOS = "en"


class TiposBusca(Enum):
    BUSCA_POR_OAB = 'busca_por_oab'
    BUSCA_POR_DOCUMENTO = 'busca_por_documento'
    BUSCA_POR_NOME = 'busca_por_nome'


class TiposMonitoramentosTribunal(Enum):
    UNICO = 'UNICO'
    NUMERO_DOCUMENTO = 'NUMDOC'
    NOME = 'NOME'


class TiposMonitoramentosDiario(Enum):
    PROCESSO = 'processo'
    TERMO = 'termo'


class FrequenciaMonitoramentoTribunal(Enum):
    DIARIA = 'DIARIA'
    SEMANAL = 'SEMANAL'


class StatusCallback(Enum):
    SUCESSO = "sucesso"
    EM_TENTATIVA = "em_tentativa"
    ERRO = "erro"


class Ordem(Enum):
    ASC = "asc"
    DESC = "desc"


class SiglaTribunais(Enum):
    SUPERIOR_TRIBUNAL_FEDERAL = STF = "STF",
    CNJ = CONSELHO_NACIONAL_JUSTICA = "CNJ",
    STJ = SUPERIOR_TRIBUNAL_JUSTICA = "STJ",
    CJF = CORREGEDORIA_JUSTICA_FEDERAL = "CJF",
    TRF1 = REGIONAL_FEDERAL_1 = "TRF1",
    TRF2 = REGIONAL_FEDERAL_2 = "TRF2",
    TRF3 = REGIONAL_FEDERAL_3 = "TRF3",
    TRF4 = REGIONAL_FEDERAL_4 = "TRF4",
    TRF5 = REGIONAL_FEDERAL_5 = "TRF5",
    TRF6 = REGIONAL_FEDERAL_6 = "TRF6",
    TST = SUPERIOR_TRABALHO = "TST",
    CSJT = CONSELHO_SUPERIOR_JUSTICA_TRABALHO = "CSJT",
    TRT1 = REGIONAL_TRABALHO_1 = "TRT-1",
    TRT2 = REGIONAL_TRABALHO_2 = "TRT-2",
    TRT3 = REGIONAL_TRABALHO_3 = "TRT-3",
    TRT4 = REGIONAL_TRABALHO_4 = "TRT-4",
    TRT5 = REGIONAL_TRABALHO_5 = "TRT-5",
    TRT6 = REGIONAL_TRABALHO_6 = "TRT-6",
    TRT7 = REGIONAL_TRABALHO_7 = "TRT-7",
    TRT8 = REGIONAL_TRABALHO_8 = "TRT-8",
    TRT9 = REGIONAL_TRABALHO_9 = "TRT-9",
    TRT10 = REGIONAL_TRABALHO_10 = "TRT-10",
    TRT11 = REGIONAL_TRABALHO_11 = "TRT-11",
    TRT12 = REGIONAL_TRABALHO_12 = "TRT-12",
    TRT13 = REGIONAL_TRABALHO_13 = "TRT-13",
    TRT14 = REGIONAL_TRABALHO_14 = "TRT-14",
    TRT15 = REGIONAL_TRABALHO_15 = "TRT-15",
    TRT16 = REGIONAL_TRABALHO_16 = "TRT-16",
    TRT17 = REGIONAL_TRABALHO_17 = "TRT-17",
    TRT18 = REGIONAL_TRABALHO_18 = "TRT-18",
    TRT19 = REGIONAL_TRABALHO_19 = "TRT-19",
    TRT20 = REGIONAL_TRABALHO_20 = "TRT-20",
    TRT21 = REGIONAL_TRABALHO_21 = "TRT-21",
    TRT22 = REGIONAL_TRABALHO_22 = "TRT-22",
    TRT23 = REGIONAL_TRABALHO_23 = "TRT-23",
    TRT24 = REGIONAL_TRABALHO_24 = "TRT-24",
    TSE = SUPERIOR_ELEITORAL = "TSE",
    TREAC = REGIONAL_ELEITORAL_ACRE = "TRE-AC",
    TREAL = REGIONAL_ELEITORAL_ALAGOAS = "TRE-AL",
    TREAP = REGIONAL_ELEITORAL_AMAPA = "TRE-AP",
    TREAM = REGIONAL_ELEITORAL_AMAZONAS = "TRE-AM",
    TREBA = REGIONAL_ELEITORAL_BAHIA = "TRE-BA",
    TRECE = REGIONAL_ELEITORAL_CEARA = "TRE-CE",
    TREDF = REGIONAL_ELEITORAL_DISTRITO_FEDERAL = "TRE-DF",
    TREES = REGIONAL_ELEITORAL_ESPIRITO_SANTO = "TRE-ES",
    TREGO = REGIONAL_ELEITORAL_GOIAS = "TRE-GO",
    TREMA = REGIONAL_ELEITORAL_MARANHAO = "TRE-MA",
    TREMT = REGIONAL_ELEITORAL_MATO_GROSSO = "TRE-MT",
    TREMS = REGIONAL_ELEITORAL_MATO_GROSSO_SUL = "TRE-MS",
    TREMG = REGIONAL_ELEITORAL_MINAS_GERAIS = "TRE-MG",
    TREPA = REGIONAL_ELEITORAL_PARA = "TRE-PA",
    TREPB = REGIONAL_ELEITORAL_PARAIBA = "TRE-PB",
    TREPR = REGIONAL_ELEITORAL_PARANA = "TRE-PR",
    TREPE = REGIONAL_ELEITORAL_PERNAMBUCO = "TRE-PE",
    TREPI = REGIONAL_ELEITORAL_PIAUI = "TRE-PI",
    TRERJ = REGIONAL_ELEITORAL_RIO_JANEIRO = "TRE-RJ",
    TRERN = REGIONAL_ELEITORAL_RIO_GRANDE_NORTE = "TRE-RN",
    TRERS = REGIONAL_ELEITORAL_RIO_GRANDE_SUL = "TRE-RS",
    TRERO = REGIONAL_ELEITORAL_RONDONIA = "TRE-RO",
    TRERR = REGIONAL_ELEITORAL_RORAIMA = "TRE-RR",
    TRESC = REGIONAL_ELEITORAL_SANTA_CATARINA = "TRE-SC",
    TRESE = REGIONAL_ELEITORAL_SERGIPE = "TRE-SE",
    TRESP = REGIONAL_ELEITORAL_SAO_PAULO = "TRE-SP",
    TRETO = REGIONAL_ELEITORAL_TOCANTINS = "TRE-TO",
    STM = SUPERIOR_TRIBUNAL_MILITAR = "STM",
    CJM1 = PRIMEIRA_CJM = "1-CJM",
    CJM2 = SEGUNDA_CJM = "2-CJM",
    CJM3 = TERCEIRA_CJM = "3-CJM",
    CJM4 = QUARTA_CJM = "4-CJM",
    CJM5 = QUINTA_CJM = "5-CJM",
    CJM6 = SEXTA_CJM = "6-CJM",
    CJM7 = SETIMA_CJM = "7-CJM",
    CJM8 = OITAVA_CJM = "8-CJM",
    CJM9 = NONA_CJM = "9-CJM",
    CJM10 = DECIMA_CJM = "10-CJM",
    CJM11 = DECIMA_PRIMEIRA_CJM = "11-CJM",
    CJM12 = DECIMA_SEGUNDA_CJM = "12-CJM",
    TJAC = JUSTICA_ESTADO_ACRE = "TJAC",
    TJAL = JUSTICA_ESTADO_ALAGOAS = "TJAL",
    TJAP = JUSTICA_ESTADO_AMAPA = "TJAP",
    TJAM = JUSTICA_ESTADO_AMAZONAS = "TJAM",
    TJBA = JUSTICA_ESTADO_BAHIA = "TJBA",
    TJCE = JUSTICA_ESTADO_CEARA = "TJCE",
    TJDF = JUSTICA_ESTADO_DISTRITO_FEDERAL = "TJDF",
    TJES = JUSTICA_ESTADO_ESPIRITO_SANTO = "TJES",
    TJGO = JUSTICA_ESTADO_GOIAS = "TJGO",
    TJMA = JUSTICA_ESTADO_MARANHAO = "TJMA",
    TJMT = JUSTICA_ESTADO_MATO_GROSSO = "TJMT",
    TJMS = JUSTICA_ESTADO_MATO_GROSSO_SUL = "TJMS",
    TJMG = JUSTICA_ESTADO_MINAS_GERAIS = "TJMG",
    TJPA = JUSTICA_ESTADO_PARA = "TJPA",
    TJPB = JUSTICA_ESTADO_PARAIBA = "TJPB",
    TJPR = JUSTICA_ESTADO_PARANA = "TJPR",
    TJPE = JUSTICA_ESTADO_PERNAMBUCO = "TJPE",
    TJPI = JUSTICA_ESTADO_PIAUI = "TJPI",
    TJRJ = JUSTICA_ESTADO_RIO_JANEIRO = "TJRJ",
    TJRN = JUSTICA_ESTADO_RIO_GRANDE_NORTE = "TJRN",
    TJRS = JUSTICA_ESTADO_RIO_GRANDE_SUL = "TJRS",
    TJRO = JUSTICA_ESTADO_RONDONIA = "TJRO",
    TJRR = JUSTICA_ESTADO_RORAIMA = "TJRR",
    TJSC = JUSTICA_ESTADO_SANTA_CATARINA = "TJSC",
    TJSE = JUSTICA_ESTADO_SERGIPE = "TJSE",
    TJSP = JUSTICA_ESTADO_SAO_PAULO = "TJSP",
    TJTO = JUSTICA_ESTADO_TOCANTINS = "TJTO",
    TJMEMG = JUSTICA_MILITAR_ESTADO_MINAS_GERAIS = "TJME-MG",
    TJMERS = JUSTICA_MILITAR_ESTADO_RIO_GRANDE_SUL = "TJME-RS",
    TJMESP = JUSTICA_MILITAR_ESTADO_SAO_PAULO = "TJME-SP"
